### ISSUE TITLE
Fix boundary property element

### ISSUE THREAD

**Issue by clausnagel** [tum-gis/citygml2-to-citygml3#4]
The name of the property element linking a `con:AbstractContruction` (such as `bldg:Building`) to one of its `con:AbstractConstructionSurface`s (such as `con:WallSurface` or `con:RoofSurface`) should be `con:constructionSurface`. However, the test datasets in the output folder all use `core:boundary` instead.

**Comment by TatjanaKutzner** [comment]
The issue can be closed. The problem doesn't occur any more due to changes in the UML model. The property element to use is `core:boundary`, `con:constructionSurface` doesn't exist any more.
